version: '3.7'

services:
  mqtt_service:
    build: ./mqtt-service
    environment:
      - MQTT_USER=mqtt_user
      - MQTT_PSWD=mqtt_useR4
      - MQTT_URL=7552e0d2600843c0a19294813d03310e.s1.eu.hivemq.cloud
      - MQTT_PORT=8883
      
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes:
      - ./mqtt-service/:/app/
    ports:
      - 8001:8000
    logging:
        driver: none 

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mqtt_service
    logging:
        driver: none 
