version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI="mongodb://root:root@mongo:27017/mongo_db"
      - DB_USER=root
      - DB_PSWD=root
    depends_on:
       - mongo

  frontend:
    build: ./frontend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./frontend/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI="mongodb://root:root@mongo:27017/mongo_db"
      - DB_USER=root
      - DB_PSWD=root
    depends_on:
       - backend

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
