version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    logging:
        driver: none
  
  core:
    build: ./core
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir app/
    volumes:
      - ./core/:/app/
    ports:
      - 8003:8000
    environment:
      - DATABASE_URI=mongodb://root:root@mongo:27017/
    depends_on:
       - mongo

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir app/ --forwarded-allow-ips=*
    volumes:
      - ./backend/:/app/
    ports:
      - 8001:8080
    environment:
      - DATABASE_URI=mongodb://root:root@mongo:27017/
    depends_on:
       - mongo

  frontend:
    build: ./frontend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  --reload-dir app/ --forwarded-allow-ips=*
    volumes:
      - ./frontend/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=mongodb://root:root@mongo:27017/
    depends_on:
       - backend

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "5986:5986"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
      - ./server-cert1.pem:/etc/nginx/server-cert1.pem
      - ./server-key1.pem:/etc/nginx/server-key1.pem
    depends_on:
      - frontend
